const ActionTypes = Object.freeze({
    PROMPT_ALL_PLAYERS: 'PROMPT_ALL_PLAYERS',
    PROMPT_CURRENT_PLAYER: 'PROMPT_CURRENT_PLAYER',
    SET_PLAYER_STATE: 'SET_PLAYER_STATE',
    DISPLACE_PLAYER: 'DISPLACE_PLAYER',
    CODE: 'CODE',
    CUSTOM: 'CUSTOM',
});

export default ActionTypes;
