const TurnPhases = Object.freeze({
    CHANGE_TURN: 'CHANGE_TURN',
    BEGIN_TURN: 'BEGIN_TURN',
    END_TURN: 'END_TURN',
    WAITING_FOR_MOVE: 'WAITING_FOR_MOVE',
    PLAYER_CHOOSING_DESTINATION: 'PLAYER_CHOOSING_DESTINATION',
    PROCESSING_MOVE: 'PROCESSING_MOVE',
    PROCESSING_EVENTS: 'PROCESSING_EVENTS',
});

export default TurnPhases;
